/**
 * Extract the measured fixture readings out of metrics.json for the UI.
 *
 *   npm run extract-metrics
 *
 * metrics.json is ~282 KB and mostly `sweep.results` (144 configs x 4
 * fixtures). Importing it whole would put all of that in the bundle for the
 * sake of a dozen numbers, so this pulls out just what the panel renders and
 * writes src/data/fixtures.json, which IS committed.
 *
 * WHAT IS DELIBERATELY NOT EXTRACTED
 * ----------------------------------
 * `sweep` and anything derived from it — recall, the usable-configuration
 * count, the threshold window. Those numbers are not valid yet: fixtures 1 and
 * 2 are two turns long and every trip threshold is at least 3, so they cannot
 * physically trip, and the sweep's "0 of 144 usable" is an artifact of that
 * rather than a result. The repo's own README says so. Shipping them in a
 * jury-facing panel would be presenting an artifact as a finding.
 *
 * What IS extracted is per-fixture measured dial readings, which are real: they
 * came out of MiniLM at a pinned revision on a recorded run.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const METRICS = resolve(HERE, "../../metrics.json");
const OUT = resolve(HERE, "../src/data/fixtures.json");

/** The package names quadrants differently from the console. Same semantics. */
const QUADRANT_ALIAS = {
  loop: "stuck",
  grind: "batch",
  explore: "productive",
  thrash: "thrash",
};

const doc = JSON.parse(readFileSync(METRICS, "utf8"));
const src = doc.detector_fixtures;

if (!src?.fixtures) {
  console.error("metrics.json has no detector_fixtures.fixtures block");
  process.exit(1);
}

const round = (n) => (typeof n === "number" ? Number(n.toFixed(4)) : n);

const fixtures = Object.entries(src.fixtures).map(([key, f]) => {
  const readings = f.readings.map((r) => ({
    action_sim: round(r.action_sim),
    obs_novelty: round(r.obs_novelty),
    quadrant: r.quadrant,
    console_quadrant: QUADRANT_ALIAS[r.quadrant] ?? r.quadrant,
    is_trip: r.is_trip,
  }));

  return {
    key,
    label: key.replace(/^\d+[a-z]?_/, "").replace(/_/g, " "),
    expect: f.expect,
    note: f.note,
    final_quadrant: f.final_quadrant,
    console_quadrant: QUADRANT_ALIAS[f.final_quadrant] ?? f.final_quadrant,
    trip_turn: f.trip_turn,
    passed: f.passed,
    preamble_turns: src.preamble_turns,
    sim_ceiling: round(f.calibrator_after_preamble?.sim_ceiling),
    readings,
  };
});

const out = {
  _comment:
    "GENERATED by web/scripts/extract_metrics.mjs from metrics.json. Do not " +
    "hand-edit. Measured dial readings only — recall and the sweep are " +
    "deliberately excluded because they are not valid yet (see the script).",
  encoder: {
    model_id: src.encoder?.model_id,
    revision: src.encoder?.revision,
    dim: src.encoder?.dim,
    seed: src.encoder?.seed,
  },
  novelty_floor: src.novelty_floor,
  novelty_floor_status: src.novelty_floor_status,
  preamble_turns: src.preamble_turns,
  all_passed: src.all_passed,
  counter_demo_holds: src.counter_demo_holds,
  quadrant_alias: QUADRANT_ALIAS,
  fixtures,
};

writeFileSync(OUT, JSON.stringify(out, null, 2) + "\n", "utf8");

const bytes = Buffer.byteLength(JSON.stringify(out));
console.log(
  `\nextracted -> src/data/fixtures.json` +
    `\n  fixtures : ${fixtures.length}` +
    `\n  readings : ${fixtures.reduce((n, f) => n + f.readings.length, 0)}` +
    `\n  size     : ${(bytes / 1024).toFixed(1)} kB (from ${(
      readFileSync(METRICS).length / 1024
    ).toFixed(0)} kB metrics.json)` +
    `\n  encoder  : ${out.encoder.model_id} @ ${out.encoder.revision?.slice(0, 8)}\n`
);
